/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_almasb_nativewindow_NativeWindow */

#ifndef _Included_com_almasb_nativewindow_NativeWindow
#define _Included_com_almasb_nativewindow_NativeWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_almasb_nativewindow_NativeWindow
 * Method:    show
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_almasb_nativewindow_NativeWindow_show
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_almasb_nativewindow_NativeWindow
 * Method:    fillRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_almasb_nativewindow_NativeWindow_fillRect
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
